### ISSUE TITLE
BMThingCLIWidgetDefinitionDownloader should ignore ptcschartcombo, ptcschartpie and dataexportfunction otherwise an invalid JSON is generated

### ISSUE THREAD

**Issue by kklorenzotesta** [BogdanMihaiciuc/ThingCLI#37]
On Thingworx 9.4 the export function finds ptcschartcombo, ptcschartpie and dataexportfunction, which are not in the ignore list. Trying to export without ignoring those widget generates an invalid json:
[widgets.json](https://github.com/BogdanMihaiciuc/ThingCLI/files/15026316/widgets.json)

the problem happen with the export of either ptcschartcombo or ptcschartpie, while the export of dataexportfunction happens correctly

**Comment by BogdanMihaiciuc** [comment]
Are there any errors in your browser console when you do this export?

It looks like the file cuts off abruptly, which to me indicates some sort issue probably unrelated to those specific widgets. Since these are not part of the built-in defaults they should be downloaded by the widget exporter (I'll look into adding them to defaults in the next releas).

**Comment by kklorenzotesta** [comment]
I took a closer look at the problem since I had no error in the console or the network.
The problem is that some widget description contains a # character, which is not transformed by the encodeURI and is interpreted probably as an anchor in the downloader href, which means that from that character going on everything is cut out.
I'm not a 100% sure that is the correct fix but replacing `encodeURI` with `encodeURIComponent` produces a well formed JSON.

**Comment by BogdanMihaiciuc** [comment]
I've implemented your fix and also added these 3 widgets to the exclusion list in version 2.1.0. These 3 widgets are now included by default via thing transformer.
